ValidAccountTypes: saving,current,salary

server:
  error:
    include-stacktrace: ON_PARAM
  port: 8082
spring: 
  application: 
    name: CAT

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
