ValidAccountTypes: saving,current,salary

debug: true
logging:
  file:
    name: logs/application.log
    path: /logs
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-stacktrace: ON_PARAM
  port: 8081
spring:
  application:
    name: Customer-Account-Tracker
  datasource:
    password: dummypassword
    url: jdbc:mysql://localhost:3306/bank
    username: bank-user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi:
      enabled: always
